name: Releases

on:
  push:
    tags:
    branch: []
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'agentic.zip'
        path: 'agentic'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "agentic.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Latest tag
      uses: EndBug/latest-tag@v1.5.1

