name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup vale
      shell: bash
      run: |
        wget https://github.com/errata-ai/vale/releases/download/v2.0.0-beta.2/vale_2.0.0-beta.2_Linux_64-bit.tar.gz
        mkdir bin && tar -xvzf vale_2.0.0-beta.2_Linux_64-bit.tar.gz -C bin
        export PATH=./bin:"$PATH"

    - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies

    - name: Install pip requirements
      shell: bash
      run: |
        pip install yamllint
        pip install markdata
        pip install pyyaml

    - name: YAML Lint
      run: yamllint -c '.yamllint.yml' agentic
      shell: bash
      
    - name: Cucumber
      run: cucumber
      shell: python
