name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.6'
    - name: Setup vale and python
      run: |
      wget https://github.com/errata-ai/vale/releases/download/v2.0.0-beta.2/vale_2.0.0-beta.2_Linux_64-bit.tar.gz
      mkdir bin && tar -xvzf vale_2.0.0-beta.2_Linux_64-bit.tar.gz -C bin
      export PATH=./bin:"$PATH"

      bundle install --jobs=3

      pip install yamllint
      pip install markdata
      pip install pyyaml
      
    - name: YAML Lint
      run: yamllint -c '.yamllint.yml' agentic
    - name: Cucumber
      run: cucumber